import numpy as np
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt

print(f"TensorFlow Version: {tf.__version__}")

# ==========================================
# 1. GENERATE SYNTHETIC SENSOR DATA
# ==========================================
# We will generate 1000 samples of normal data and 1000 of anomaly data

# Normal Data: Temp 20-28°C, Humidity 30-60%
normal_temp = np.random.uniform(20, 28, 1000)
normal_hum = np.random.uniform(30, 60, 1000)
normal_labels = np.zeros(1000) # 0 = Normal

# Anomaly Data: Temp 32-45°C (overheating), Humidity 80-100% (condensation/leak)
anomaly_temp = np.random.uniform(32, 45, 1000)
anomaly_hum = np.random.uniform(80, 100, 1000)
anomaly_labels = np.ones(1000) # 1 = Anomaly

# Combine and shuffle
X_temp = np.concatenate((normal_temp, anomaly_temp))
X_hum = np.concatenate((normal_hum, anomaly_hum))
y = np.concatenate((normal_labels, anomaly_labels))

# ==========================================
# 2. NORMALIZE THE DATA
# ==========================================
# Neural networks work best with inputs between 0.0 and 1.0.
# We map Temp (0-50°C) to 0.0-1.0 and Humidity (0-100%) to 0.0-1.0
# IMPORTANT: This exact math MUST be used in your ESP32 C++ code!

X_temp_norm = (X_temp - 0.0) / (50.0 - 0.0)
X_hum_norm = (X_hum - 0.0) / (100.0 - 0.0)

# Stack features into a single array: [[temp1, hum1], [temp2, hum2], ...]
X = np.column_stack((X_temp_norm, X_hum_norm))

# ==========================================
# 3. BUILD AND TRAIN THE MODEL
# ==========================================
# A very small Neural Network designed to fit in ESP32 RAM
model = keras.Sequential([
    keras.layers.Dense(16, activation='relu', input_shape=(2,)),
    keras.layers.Dense(8, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid') # Outputs 0.0 to 1.0 probability
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

print("Training model...")
history = model.fit(X, y, epochs=50, batch_size=32, validation_split=0.2, verbose=1)

# ==========================================
# 4. CONVERT TO TENSORFLOW LITE (QUANTIZED)
# ==========================================
print("Converting to TFLite...")
converter = tf.lite.TFLiteConverter.from_keras_model(model)
# Optimize for size (converts weights to 8-bit integers)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()

# Save the binary model
with open("anomaly_model.tflite", "wb") as f:
    f.write(tflite_model)

# ==========================================
# 5. CONVERT TO C-ARRAY HEADER FILE
# ==========================================
# This replaces the need for the Linux 'xxd' command
def generate_h_file(tflite_binary, filename="dht_anomaly_model.h"):
    print(f"Generating {filename}...")
    hex_array = [hex(b) for b in tflite_binary]
    
    with open(filename, "w") as f:
        f.write("#ifndef DHT_ANOMALY_MODEL_H\n")
        f.write("#define DHT_ANOMALY_MODEL_H\n\n")
        f.write("#include <Arduino.h>\n\n")
        f.write("// Automatically generated by Google Colab\n")
        f.write("alignas(8) const unsigned char dht_anomaly_model_tflite[] = {\n  ")
        
        # Write hex values with nice formatting
        for i, val in enumerate(hex_array):
            f.write(f"{val}, ")
            if (i + 1) % 12 == 0:
                f.write("\n  ")
                
        f.write("\n};\n\n")
        f.write(f"const unsigned int dht_anomaly_model_tflite_len = {len(hex_array)};\n\n")
        f.write("#endif // DHT_ANOMALY_MODEL_H\n")

generate_h_file(tflite_model)

# ==========================================
# 6. DOWNLOAD THE FILE
# ==========================================
from google.colab import files
print("Downloading C-header file to your computer...")
files.download("dht_anomaly_model.h")